/*******************************************************/
/* Macro SCScale */
/*******************************************************/
%macro SCScale(BasePoints, BaseOdds, PDO, M_alpha, M_beta);
/* this macro calculates alpha, beta to scale the scorecard
   such that points=alpha + beta (ln odds) 
   beta = pdo/ln(2)
   alpha=basePoints - beta * (ln base odds)
*/
%local bb;
%let bb=%sysevalf(&PDO / %sysfunc(log(2)));
%let &M_Beta = &bb;
%let &M_alpha= %sysevalf(&BasePoints - &bb * %sysfunc(log(&BaseOdds)));
%mend;



/*******************************************************/
/* Macro GenSCDS */
/*******************************************************/
%macro GenSCDS(ParamDS, Lib, DVName, BasePoints, BaseOdds, PDO, SCDS);
/*
Generation of a scorecard dataset using the predictive model stored in ParamDS
The datasets are in the library LIB
*/
 
/* first, get alpha and beta from the base points and pdo */
%local alpha beta;
%let alpha=;
%let beta=;
%SCScale(&BasePoints, &BaseOdds, &PDO, alpha, beta);

/* read the model coefficients from the model dataset */

proc transpose data =&ParamDS out=temp_mpt;
run;


/* remove ignore variables and ln likeilhood value, and get the intercept */
%local Intercept;

data temp_mptc;
 set temp_mpt;
length VarName $32.;
length MapDS  $32.;
length WOEDS $32.;
if _Name_ eq 'Intercept' then do;
  call symput('Intercept', compress(&DVName));
  delete;
  end;
 /* Make all names upper case */
  *_Name_=upcase(_Name_);

 /* restore variable names, names of maps, WOE datasets */
  ix=find(upcase(_Name_),'_WOE')-1;
  if ix >0 then VarName=substr(_Name_,1,ix);
  MapDS=compress(VarName)||'_MAP';
  BinName=compress(VarName)||'_b';
  WOEDS=_Name_;
  Parameter=&DVName;

  if _Name_ ne '_LNLIKE_' and &DVName ne . ;
  keep VarName BinName MapDS WOEDS Parameter;
run;

/* Scorecard Base points = alpha + intercept * beta */
  %local SCBase; 
  %let SCBase = %sysfunc(int(&alpha + &beta * &Intercept));


%local i N;
data _null_;
 set temp_mptc;
  call symput('N',compress(_N_));
run;
%do i=1 %to &N;
 %local V_&i P_&i WOE_&i Map_&i;
%end;

/* Start merging the scorecard table */
data _null_;
 set temp_mptc;
  call symput('V_'||left(_N_),compress(VarName));
  call symput('B_'||left(_N_),compress(BinName));
  call symput('P_'||left(_N_),compress(Parameter));
  call symput('WOE_'||left(_N_),"&Lib.."||compress(WOEDS));
  call symput('Map_'||left(_N_),"&lib.."||compress(MapDS));
run;

proc sql noprint;
 create table &SCDS (VarName char(80), UL num, LL num,  Points num);
 insert into &SCDS values('_BasePoints_' , 0    , 0     ,  &SCBase);
run; quit;
%do i=1 %to &N;

   data temp1;
     set &&WOE_&i;
	   bin=&&B_&i;
	   VarName="&&V_&i";
	   ModelParameter=&&P_&i;
   run;

   proc sort data=temp1;
    by bin;
   run;
   /* check the type of the nominal variable */
	proc contents data=&&Map_&i out=temp_cont nodetails noprint;
	run;
	%local MapType;
	proc sql noprint; 
	 select Type into :MapType from temp_cont where upcase(Name)='CATEGORY';
	run; quit;
	%if &MapType =1 %then %do; /* numeric variable */
	 Data &&Map_&i;
	  set &&Map_&i;
	   N_category=Category;
	   drop category;
	 run;
	%end;

   proc sort data=&&Map_&i;
    by bin;
   run;

    data temp_v;
     merge temp1 &&Map_&i;
	  by bin;
	run;

	proc sort data=temp_v;
	 by VarName;
	run;

    proc sort data=&SCDS;
	 by VarName;
    run;

    data temp_all;
	 merge &&SCDS temp_v;
	  by VarName;
	run;

    Data &SCDS;
	  set temp_all;
	  drop &&B_&i;
	run;

%end;
/* Calculate the points and drop unnecessary varibles, 
   and setup the variable type for ease of generation of
   code: VarType 1 = continuous, 2=nominal string, 3=nominal numeric,
         0= Base Points */

data &SCDS;
  set &SCDS;
   if VarName = '_BasePoints_' then VarType=0;
   else do;
       Points=-WOE*ModelParameter * &beta ;
        if UL ne . and LL ne . then VarType=1;
          else if N_Category eq . then VarType=2;
	        else VarType=3;
	end;

   drop WOE bin ModelParameter;
run;

proc sort data=&SCDS;
 by VarType VarName;
run;



/* clean up workspace */
proc datasets library=work nodetails;
delete temp1 temp_all temp_cont temp_mpt temp_mptc temp_v;
run; quit;



%mend;


/*******************************************************/
/* Macro SCSASCode */
/*******************************************************/
%macro SCSasCode(SCDS,BasePoints, BaseOdds, PDO, IntOpt,FileName);
/* writing the scorecard generated by the scorecard dataset to an output
  file FileName generating SAS code
  If The option IntOpt=1 then we convert the points to integer values
  otherwise they are left as numbers */

/* direct the output to the filename */

proc sort data=&SCDS;
by VarType VarName;
run;

data _null_;
set &SCDS nobs=nx;
by VarType VarName;
file "&FileName";
length cond $300.;
length value $300.;

if _N_ =1 then do;
	put '/*********************************************/' ;
	put '/*********************************************/';
	put '/***** Automatically Generated Scorecard *****/';
	put '/*********************************************/';
	put '/************    SAS CODE             ********/';
	put;
	put '/* Scorecard Scale : */';
	put "/*  Odds of [ 1 : &BaseOdds ] at  [ &BasePoints ] Points ";
    put "     with PDO of [ &PDO ] */";
	put; 
	put '/*********************************************/';
	put '/*********************************************/';
	put ;


	put '/********** START OF SCORING DATA STEP *******/';
	put '/*********************************************/';
	put '/*********************************************/';
	put;
	put 'DATA SCORING;        /********** Modify ************/';
	put ' SET ScoringDataset; /********** Modify ************/';
	put;
	put '/*********************************************/';
	put '/*********************************************/';
end; 

/* print the dataset RulesDS */


%if &IntOpt=1 %then xPoints=int(Points);
%else xPoints=Points; ;

if VarName="_BasePoints_" then do;
	put '/*********************************************/';
	put "/* Base Points   */";
	put '/*********************************************/';
put "Points=" xPoints ";";
                            end;
 else do;
   if first.VarName then do;
	put '/*********************************************/';
	put "/* Variable : " VarName "    *****/";
	put '/*********************************************/';
                      end;
    value= "  THEN  Points=Points +("||compress(xPoints)||");";

    /* The rule */
    if VarType=1 then  do;/* continuous */
	if first.VarName then  cond='IF '||compress(VarName)||' LE ('||compress(UL) || ') '; 
	else if last.VarName then cond='IF '||compress(VarName)||' GT ('|| compress(LL)||')';
    else cond='IF '||compress(VarName)||' GT ('|| compress(LL)||') AND '||compress(VarName)||' LE ('||compress(UL) || ') '; 
                       end; 
    else if VarType=2 then /* nominal string */
	cond = 'IF '||compress(VarName)||' = '|| quote(compress(Category)) ; 

	else /* nominal numeric */
	cond='IF '||compress(VarName)||' = ('|| compress(N_Category)||') '; 
	
	put "      " cond value;

 end;

 if _N_=Nx then do;
	put 'RUN;'; 
	put;
	put '/*************END OF SCORING DATA STEP *******/';
	put '/*********************************************/';
	end;
run;


%mend;


/* Generate the Scorecard Points dataset */
%let ModelDS=cc.Model_Params;
%let DVName=bad_good;
%let Lib=cc;
%let BasePoints=600;
%let BaseOdds=60;
%let PDO=20;
%let SCDSName=CSCDS;
%GenSCDS(&MOdelDS,&Lib, &DVName, &BasePoints, &BaseOdds, &PDO, &SCDSName);


/* Use the scorecard points dataset to generate SAS code */
%let BasePoints=600;
%let BaseOdds=60;
%let PDO=20;
%let File=E:\SAS\Competition\CreditScoreCard.sas;
%SCSasCode(CSCDS,&BasePoints, &BaseOdds, &PDO, 1,&File);


/*由于运行过程出现变量的缩写，故对原始数据集rename*/
%let dir=E:\SAS\;
data ScoringDataset;
set "&dir credit_mini.sas7bdat";
rename DEP_SA_OPEN_TENURE_DAYS=DSOTD
       DEP_SA_AVG_TENURE_DAYS=DSATD
       DEP_SA_LAST_TENURE_DAYS=DSLTD
       DEP_SA_FGCR_ACCOUNT_CNT=DSFAC
	   CHANNEL_CTR_CREDIT_CNT=CCCC
	   L6DEP_SA_MOTH_MAX_OUT_AMT=L6SMMOA
	   L3DEP_SA_DAY_MAX_OUT_AMT=L3SDMOA
       L6DEP_SA_MOTH_MAX_IN_AMT=L6SMMIA
	   L3DEP_SA_MOTH_MAX_OUT_AMT=L3SMMOA
	   DEP_SA_DAY_MAX_OUT_AMT=DSDMOA
	   DEP_TD_FLAG=DTF
	   CUST_SALARY_FINANCIAL_FLAG=CSFF
	   CUST_STAD_PLATINUM_FLAG=CSPF
	   CUST_INTERNATIONAL_DIAMOND_FLAG=CIDF
	   TOT_REPAY_FLAG=TRF
	   CRED_FLAG=CF
	   GENDER=GENDER
	   ;
run;
